[build]
  publish = "."
  command = "echo 'No build needed - static files'"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
